spring:
  application:
    name: b3invest-manager

  datasource:
    url: jdbc:h2:mem:b3invest
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

# MYSQL Database configuration
#  jpa:
#    show-sql: false
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#      dialect: org.hibernate.dialect.MySQL8Dialect
#     dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  jmx:
#    enabled: false
#  datasource:
#    url: jdbc:mysql://localhost:3306/b3invest?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
#    username:
#    password:

server:
  port: ${PORT:0}
# port: 8001
#  servlet:
#    context-path: /manager

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




